// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website_banhang.Models;

#nullable disable

namespace Website_banhang.Migrations
{
    [DbContext(typeof(QlbhContext))]
    partial class QlbhContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Website_banhang.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__D54EE9B4FEDDD521");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Website_banhang.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int?>("OrderItem")
                        .HasColumnType("int")
                        .HasColumnName("order_item");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_price");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__4659622979A1F315");

                    b.HasIndex("OrderItem");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Website_banhang.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItem1")
                        .HasColumnType("int")
                        .HasColumnName("order_item");

                    b.Property<decimal?>("OrderPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("order_price");

                    b.Property<int?>("OrderQuantity")
                        .HasColumnType("int")
                        .HasColumnName("order_quantity");

                    b.Property<decimal?>("OrderTotalprice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("order_totalprice");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.HasKey("OrderItem1")
                        .HasName("PK__Order_it__32745CF5A37EC49E");

                    b.HasIndex("ProductId");

                    b.ToTable("Order_item");
                });

            modelBuilder.Entity("Website_banhang.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<string>("Fillter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("product_description");

                    b.Property<string>("ProductImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("product_image");

                    b.Property<string>("ProductName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("product_name");

                    b.Property<decimal?>("ProductPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("product_price");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__47027DF5F81DB02A");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Website_banhang.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("RoleName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__760965CCABDDF7B6");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Website_banhang.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createAt");

                    b.Property<string>("Fillter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fillter");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("UserAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_address");

                    b.Property<int?>("UserAge")
                        .HasColumnType("int")
                        .HasColumnName("user_age");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPhone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_phone");

                    b.HasKey("UserId")
                        .HasName("PK__User__B9BE370F9F35DECF");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Website_banhang.Models.Order", b =>
                {
                    b.HasOne("Website_banhang.Models.OrderItem", "OrderItemNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("OrderItem")
                        .HasConstraintName("FK__Order__order_ite__571DF1D5");

                    b.HasOne("Website_banhang.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Order__user_id__5629CD9C");

                    b.Navigation("OrderItemNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Website_banhang.Models.OrderItem", b =>
                {
                    b.HasOne("Website_banhang.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Order_ite__produ__534D60F1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Website_banhang.Models.Product", b =>
                {
                    b.HasOne("Website_banhang.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Product__categor__5070F446");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Website_banhang.Models.User", b =>
                {
                    b.HasOne("Website_banhang.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__User__role_id__4BAC3F29");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Website_banhang.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Website_banhang.Models.OrderItem", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Website_banhang.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Website_banhang.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Website_banhang.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
